### ISSUE TITLE
layers.py 里面缺少的layer_meta文件没有找到

### ISSUE THREAD

**Issue by Yarkona** [wilburOne/AdversarialNameTagger#1]
您好！在dnn_pytorch/seq_labeling_naacl/layers.py 文件开头，第14行

from layers_meta import meta_linear_ops

其中layers_meta文件没有找到，能否麻烦您提供下？

**Comment by wilburOne** [comment]
> 您好！在dnn_pytorch/seq_labeling_naacl/layers.py 文件开头，第14行
> 
> from layers_meta import meta_linear_ops
> 
> 其中layers_meta文件没有找到，能否麻烦您提供下？

It was not used in this project. I just removed it. Should be able to run. Thanks!!

**Comment by Yarkona** [comment]
Thanks a lot !
